INSERT INTO hobbies (HOBBY_NAME) VALUES ('SPORTS');
INSERT INTO hobbies (HOBBY_NAME) VALUES ('CRAFTS');
INSERT INTO hobbies (HOBBY_NAME) VALUES ('COLLECTING');
INSERT INTO hobbies (HOBBY_NAME) VALUES ('DANCING');
INSERT INTO hobbies (HOBBY_NAME) VALUES ('LANGUAGES');
INSERT INTO hobbies (HOBBY_NAME) VALUES ('TRAVEL');
INSERT INTO hobbies (HOBBY_NAME) VALUES ('PLANT_GROWING');
INSERT INTO hobbies (HOBBY_NAME) VALUES ('OTHER');